### ISSUE TITLE
Manifest serialisation from Python

### ISSUE THREAD

**Issue by jdub** [tableau/tableau-migration-sdk#18]
Hello gang,

I looked through the docs but couldn't see anything that mentioned whether you expect migration runs to be repeatable.

i.e. if I do a run today and observe some failures, make some changes and do a run tomorrow, will it create all new items, or is it designed to replace existing items?

While I can't see any common GUIDs in POST/PUT calls between runs, I can see some `overwrite=true` query parameters that might suggest there's an expectation of repeatability. 

Thanks,
Jeff

**Comment by dngtableau** [comment]
Hi Jeff,

Yes, it's designed to be repeatable. For multiple migration runs, you can pass in the previous manifest as a secondary argument to the execute method. Please see the python test app for additional details https://github.com/tableau/tableau-migration-sdk/blob/main/tests/Python.TestApplication/main.py.

Yes currently content types are expected to be replaced by subsequent runs. If you have questions about specific content types, feel free to ping this thread and we can answer in more detail.

Best,
Derek

**Comment by jdub** [comment]
@dngtableau great news, i wondered if the manifest stuff was relevant! i'll plug that in to my runner and see how i go – thanks for your help :-)

**Comment by dngtableau** [comment]
Unfortunately we don't have an example yet. We're looking to add more features and documentations as we add more content types.

Can you share any logs and your migration plan above? The behavior above does seems odd. We would need more information to investigate the behavior.

**Comment by jdub** [comment]
I have now upgraded to 4.1.0, which is looking much nicer for Python! Still no manifest load/save examples, though it's easier to look at the resulting manifest object.

(I'm not on a fast enough network to run any full simulations, so I'll get back to you about the behaviour.)

**Comment by jdub** [comment]
I see 4.2.0 mentions manifest (de)serialisation in the release notes and in the example! 👍🏻

**Comment by rbanderton** [comment]
Closing as complete.
