### ISSUE TITLE
Documentation and examples suggestions

### ISSUE THREAD

**Issue by jdub** [tableau/tableau-migration-sdk#20]
It's currently fairly hard to figure out and use this project with Python. It's early days for the project, and choosing Python is essentially choosing hard mode due to the multi-language challenge, but I imagine you aspire for Python to be easy mode. :-)

[Hooks in Python](https://tableau.github.io/migration-sdk/samples/python_hooks.html):
- this was just enough to help me understand how to write a filter in Python
- `filtered` is a C# List, which is not obvious from the first example (though List is imported in the second example)
- `filtered.add` → `filtered.Add` because it's a C# List

Manifest serialisation:
- because this is so important for [repeatability and reliability](https://github.com/tableau/tableau-migration-sdk/issues/18), a worked example would be incredibly helpful
- I was pointed to the [Python test application](https://github.com/tableau/tableau-migration-sdk/blob/main/tests/Python.TestApplication/main.py) for an example of manifest serialisation, but it's heavily dependent on code in the source repo, e.g. `from Tableau.Migration.TestComponents.Engine.Manifest import MigrationManifestSerializer`

**Comment by dngtableau** [comment]
Thanks for the feedback! I've noted this in our system and we will continue working on adding more documentation and content types to provide more clarity and examples for our customers.

**Comment by aaronlower** [comment]
@jdub - come join our DataDev slack channel - https://www.tableau.com/developer
