### ISSUE TITLE
Download Custom View: REST API does not support access to the given resource

### ISSUE THREAD

**Issue by peterg66** [tableau/tableau-migration-sdk#22]
Dear team,

I tried to download custom view from my Tableau Server (2023.1) using REST API 
GET /api/*api-version*/sites/*site-id*/customviews/*customview-id*/content
as indicated here (migrate custom views > step two)
https://help.tableau.com/current/api/migration_sdk/en-us/docs/ref_download_custom_view.html
but I got the error below
    <error code="404008">
        <summary>Resource Not Found</summary>
        <detail>API version '3.19' does not support access to the given resource.</detail>
    </error>

REST API works correctly when I get the custom views list 
GET /api/api-version/sites/site-luid/customviews
and the custom view image too
GET /api/api-version/sites/site-luid/customviews/custom-view-luid/image
but not with the custom view’s content.

Thanks,
Pietro

**Comment by aaronlower** [comment]
Hi Peter! Tableau Server will need to be 23.3 or newer and you'll need to use API version "exp"

**Comment by peterg66** [comment]
Hi Aaron,
thanks for your feedback, how can I use the API version ‘exp’? I didn’t find any indication in the documentation
KR
Pietro

Da: Aaron Lower ***@***.***>
Inviato: mercoledì 5 giugno 2024 16:33
A: tableau/tableau-migration-sdk ***@***.***>
Cc: Gentini Pietro ***@***.***>; Author ***@***.***>
Oggetto: Re: [tableau/tableau-migration-sdk] Download Custom View: REST API does not support access to the given resource (Issue #22)


Hi Peter! Tableau Server will need to be 23.3 or newer and you'll need to use API version "exp"

**Comment by drache42** [comment]
@peterg66, 
The exp is not documented as it's experimental. To use it, just replace the `api-version` which in your example was probably `3.19` in the URL with `exp`.

**Comment by aaronlower** [comment]
this will get much easier when we include custom views as a supported asset type in an upcoming release

**Comment by peterg66** [comment]
Hi Aaron, I agree, thanks for your support.
KR
Pietro
