### ISSUE TITLE
Download Custom Views - Inconsistent Results

### ISSUE THREAD

**Issue by ErlinaAC** [tableau/tableau-migration-sdk#29]
I'm following these [steps](https://help.tableau.com/current/api/migration_sdk/en-us/docs/migrating_custom_views.html) for my company's Tableau Cloud migration. Currently, I'm on the [Download Custom Views](https://help.tableau.com/current/api/migration_sdk/en-us/docs/ref_download_custom_view.html) step. I am using Alteryx to create this whole process, but also using postman web and application for testing purposes. 

When running the workflow/request in all of the tools mentioned, we're getting inconsistent results. Sometimes I get a successful result (200) and other times I get an unsuccessful result (404 - page not found). Our theory is that because the server has 3 nodes with a load balancer of some sort, it's causing this inconsistency. Our Tableau team didn't seem to see this issue in their environment, but they also have a load balancer. Is there a specific configuration on our server to prevent this issue from arising? 
![Screenshot 2024-08-02 115957](https://github.com/user-attachments/assets/8f3f5e38-14e8-469e-b992-7fa67c8deeb7)

**Comment by aaronlower** [comment]
our team has also seen some inconsistent behavior, luckily this API is scheduled to be fully supported with the next version in the next release (approx. October) which should resolve the issue. You should also see updates to the documentation and it will be move to the official documentation section on the Tableau API page.

**Comment by ErlinaAC** [comment]
Great to hear thanks!
