### ISSUE TITLE
Is Migrating Custom Views Possible Right Now? 

### ISSUE THREAD

**Issue by ErlinaAC** [tableau/tableau-migration-sdk#30]
Our company's TAM directed us to these [steps](https://help.tableau.com/current/api/migration_sdk/en-us/docs/migrating_custom_views.html) to help us migrate our Tableau Server's custom views to our new Tableau Cloud environment. However, I had a concerning conversation with one of our Tableau Support guys helping us with our ticket, stating that migrating is theoretically impossible due to Postgres not being in the picture for Cloud. Basically, stating that moving forward with this workflow would be useless. 

Can you please confirm if this is true? I know in my other ticket, I was told that the API will be fully supported in approx. October. However, my team is expecting me to get this done before October and if its not possible at the moment, that's fine, but if it is then I'll keep working on it. 

Also, it states in the second [step](https://help.tableau.com/current/api/migration_sdk/en-us/docs/migrating_custom_views.html) that 

> For each custom view, use [Download Custom View](https://help.tableau.com/current/api/migration_sdk/en-us/docs/ref_download_custom_view.html) to download XML.

However, I don't get a response that looks like XML. Instead I get something like the attached, is that what I should expect?
![Screenshot 2024-08-06 094911](https://github.com/user-attachments/assets/d324378b-b384-4519-86c2-3481425840ea)

**Comment by aaronlower** [comment]
Migrating custom views is definitely possible but its not currently supported by the SDK as an asset type [we are working hard to support it in the next few weeks, even before October]. You would need to call the API directly instead of using the SDK as the middle layer / orchestrator.
