### ISSUE TITLE
Typo in XmlArrayItem for Views in CommitWorkbookPublishRequest.cs

### ISSUE THREAD

**Issue by Jodolod** [tableau/tableau-migration-sdk#31]
Hello,

there seems to be a typo in the XmlArrayItem for views. Both the XmlArray and the XmlArrayItem are called views but if I read the REST Api documentation correctly the XmlArray should be called views and the XmlArrayItem should be called view or am I mistaking?

I attached the example from the documentation below

Best

```xml
--boundary-string
Content-Disposition: name="request_payload"
Content-Type: text/xml
<tsRequest>
  <workbook name="workbook-name" showTabs="show-tabs-flag" thumbnailsUserId="user-luid" >
    <connections>
      <connection serverAddress="server-address" serverPort="port-number">
        <connectionCredentials name="connection-username" password="connection-password"
           embed="embed-flag" oAuth="oauth-flag" />
	  </connection>
	</connections>
	<views>
      <view name="view-name" hidden="hide-view-flag" />
	</views>
	<project id="project-id"/>
  </workbook>
</tsRequest>
--boundary-string--
```

[Docs](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooks_and_views.htm#publish_workbook)

**Comment by pvshn** [comment]
The fix is in [v4.3.0](https://github.com/tableau/tableau-migration-sdk/releases/tag/release%2F4.3.0)
