### ISSUE TITLE
Run the code will send message to other member in tableau cloud and they cannot login tableau after they receive email

### ISSUE THREAD

**Issue by williequ** [tableau/tableau-migration-sdk#34]
I have a issues. I run the code its working, but one question is it really slow, and it will send message to my manager, and the message is about: You've Been Invited to Tableau Cloud, after he received email, he cannot login to his the tableau cloud account anymore, the error message is MFA not current. Also, for this code, can i modify the data source during the migration like in the source the data source is postgre.com.au and in the destination is postgres2.com.au
Thanks

**Comment by pvshn** [comment]
Before you run a migration, you should follow the [Pre-Migration Checklist](https://help.tableau.com/current/api/migration_sdk/en-us/docs/how_to_migrate.html). For your case, look at Step 4 that iinvolves setting up [authentication](https://help.tableau.com/current/online/en-us/security_auth.htm).

Did you or the site admin already complete this step?
