### ISSUE TITLE
Incomplete migration of Custom view: Few are migrated and others are failing

### ISSUE THREAD

**Issue by anandsai1234** [tableau/tableau-migration-sdk#40]
Hi Team,

We were trying to migrate only custom views related to a particular dashboard. We wrote a filter to filter out only those views in that workbook. Some views got migrated and others did not. We are getting error:

`{
                "ClassName": "System.Net.Http.HttpRequestException",
                "Exception": {
                    "Message": "Response status code does not indicate success: 404 (Not Found).",
                    "Type": "System.Net.Http.HttpRequestException",
                    "Source": "System.Net.Http",
                    "StackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\n   at Tableau.Migration.Net.DefaultHttpResponseMessage.EnsureSuccessStatusCode()\n   at Tableau.Migration.Api.IHttpResponseMessageExtensions.DownloadResultAsync(Task1 getResponseAsync, CancellationToken cancel)",
                    "HelpLink": null,
                    "HResult": -2146233088
                }
            }
        ]
    },

`
It would be great if someone could help me why this error is occurring and how to fix it.

**Comment by drache42** [comment]
Thank you for this bug report.

We have noticed this internally as well and we're working understanding the issue.

**Comment by anandsai1234** [comment]
Hey Team, any update on why the issue is happening?

**Comment by drache42** [comment]
This was a bug in Tableau Server. Upgrading to the latest version will fix this.
